version: '3'

volumes:
    level_data: {}

networks:
  front-tier:
  back-tier:

services:
  traefik:
    image: traefik #The official Traefik docker image
    command: --api --docker #Enables the web UI and tells Træfik to listen to docker
    ports:
      - "80:80"     #The HTTP port
      - "8080:8080" #The Web UI (enabled by --api)
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #So that Traefik can listen to the Docker events
      - ${PWD}/traefik.log:/var/log/traefik.log
      - ${PWD}/traefik.toml:/etc/traefik/traefik.toml
      - ${PWD}/acme:/etc/traefik/acme
  lerndieuhr:
    image: mokikz/lerndieuhr:v5.3
    labels:
      - "traefik.port=8080"
      - "traefik.backend=lerndieuhr"
      - "traefik.frontend.rule=Host:lerndieuhr.mokikz.de"
    networks:
      - back-tier
